[package]
name = "struo-celox"
description = "Celox simulation adapter for Struo technology-mapped netlists"
publish = ["crates-io"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
celox = "=0.3.1"
struo-ir.workspace = true
struo-target-ecp5.workspace = true

[dev-dependencies]
struo-rtl.workspace = true
struo-synth.workspace = true

[lints]
workspace = true
