[package]
name = "struo-target-ecp5"
description = "Lattice ECP5 synthesis, verification, and place-and-route target"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
struo-sim = { path = "../struo-sim" }

[lints]
workspace = true
