[package]
name = "struo-example-axi4-smartconnect"
description = "Veryl AXI4 SmartConnect synthesis and verification example for Struo"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
struo.workspace = true

[dev-dependencies]
celox = { git = "https://github.com/celox-sim/celox.git", rev = "7ff0dd2b8c4a92efd9a1aabe376240c6dff3f9c9" }

[lints]
workspace = true
