[package]
name = "struo-synth"
description = "Synthesis passes and pipeline for Struo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
struo-formal.workspace = true
struo-ir.workspace = true
struo-rtl.workspace = true

[lints]
workspace = true
